"""add trust_score_snapshots

Revision ID: 3e5422bdcfdf
Revises: f6fd9ee3f6ac
Create Date: 2026-08-08 13:50:51.658431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5422bdcfdf'
down_revision = 'f6fd9ee3f6ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trust_score_snapshots',
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('audit_readiness', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('engine', sa.String(length=40), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_score_snapshots_computed_at'), 'trust_score_snapshots', ['computed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trust_score_snapshots_computed_at'), table_name='trust_score_snapshots')
    op.drop_table('trust_score_snapshots')
    # ### end Alembic commands ###
