"""initial schema

Revision ID: f6fd9ee3f6ac
Revises: 
Create Date: 2026-08-08 09:20:05.875829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6fd9ee3f6ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('dataset_type', sa.Enum('EMPLOYEES', 'DEVICES', 'CLOUD_ASSETS', 'APPLICATIONS', 'VENDORS', 'POLICIES', 'CONTROLS', 'RISKS', 'EVIDENCE', 'FINDINGS', 'REPORTS', 'PERSONAL_DATA_INVENTORY', 'CONSENT_RECORDS', 'IAM_RECORDS', 'AUDIT_LOGS', name='dataset_type', native_enum=False, length=40), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='ingestion_status', native_enum=False, length=20), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('rows_errored', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_dataset_type'), 'ingestion_jobs', ['dataset_type'], unique=False)
    op.create_table('applications',
    sa.Column('application_id', sa.String(length=20), nullable=False),
    sa.Column('application_name', sa.String(length=150), nullable=False),
    sa.Column('owner_department', sa.String(length=100), nullable=False),
    sa.Column('authentication_method', sa.String(length=50), nullable=False),
    sa.Column('uses_mfa', sa.Boolean(), nullable=False),
    sa.Column('encryption_enabled', sa.Boolean(), nullable=False),
    sa.Column('data_classification', sa.String(length=30), nullable=False),
    sa.Column('internet_facing', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('application_name')
    )
    op.create_index(op.f('ix_applications_data_classification'), 'applications', ['data_classification'], unique=False)
    op.create_index(op.f('ix_applications_internet_facing'), 'applications', ['internet_facing'], unique=False)
    op.create_index(op.f('ix_applications_owner_department'), 'applications', ['owner_department'], unique=False)
    op.create_index(op.f('ix_applications_risk_level'), 'applications', ['risk_level'], unique=False)
    op.create_table('employees',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=False),
    sa.Column('manager_id', sa.String(length=20), nullable=True),
    sa.Column('office_location', sa.String(length=100), nullable=False),
    sa.Column('employment_type', sa.String(length=30), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('password_length', sa.Integer(), nullable=False),
    sa.Column('password_last_changed', sa.Date(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('account_status', sa.String(length=30), nullable=False),
    sa.Column('device_id', sa.String(length=20), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_account_status'), 'employees', ['account_status'], unique=False)
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_device_id'), 'employees', ['device_id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_table('ingestion_logs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', name='ingestion_log_level', native_enum=False, length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_row', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_logs_job_id'), 'ingestion_logs', ['job_id'], unique=False)
    op.create_table('policies',
    sa.Column('policy_id', sa.String(length=30), nullable=False),
    sa.Column('policy_name', sa.String(length=200), nullable=False),
    sa.Column('framework', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('owner_department', sa.String(length=100), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index(op.f('ix_policies_category'), 'policies', ['category'], unique=False)
    op.create_index(op.f('ix_policies_framework'), 'policies', ['framework'], unique=False)
    op.create_index(op.f('ix_policies_mandatory'), 'policies', ['mandatory'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.String(length=20), nullable=False),
    sa.Column('framework', sa.String(length=30), nullable=False),
    sa.Column('generated_date', sa.Date(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('critical_findings', sa.Integer(), nullable=False),
    sa.Column('high_findings', sa.Integer(), nullable=False),
    sa.Column('medium_findings', sa.Integer(), nullable=False),
    sa.Column('low_findings', sa.Integer(), nullable=False),
    sa.Column('compliance_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_reports_compliance_status'), 'reports', ['compliance_status'], unique=False)
    op.create_index(op.f('ix_reports_framework'), 'reports', ['framework'], unique=False)
    op.create_table('vendors',
    sa.Column('vendor_id', sa.String(length=20), nullable=False),
    sa.Column('vendor_name', sa.String(length=150), nullable=False),
    sa.Column('service_category', sa.String(length=100), nullable=False),
    sa.Column('iso27001_certified', sa.Boolean(), nullable=False),
    sa.Column('soc2_certified', sa.Boolean(), nullable=False),
    sa.Column('dpdp_compliant', sa.Boolean(), nullable=False),
    sa.Column('risk_rating', sa.String(length=20), nullable=False),
    sa.Column('contract_expiry', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('vendor_id'),
    sa.UniqueConstraint('vendor_name')
    )
    op.create_index(op.f('ix_vendors_risk_rating'), 'vendors', ['risk_rating'], unique=False)
    op.create_index(op.f('ix_vendors_service_category'), 'vendors', ['service_category'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=True),
    sa.Column('application_id', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('geo_location', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_application_id'), 'audit_logs', ['application_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_employee_id'), 'audit_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_geo_location'), 'audit_logs', ['geo_location'], unique=False)
    op.create_index(op.f('ix_audit_logs_result'), 'audit_logs', ['result'], unique=False)
    op.create_index(op.f('ix_audit_logs_risk_score'), 'audit_logs', ['risk_score'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('cloud_assets',
    sa.Column('resource_id', sa.String(length=30), nullable=False),
    sa.Column('cloud_provider', sa.String(length=20), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('owner_employee_id', sa.String(length=20), nullable=True),
    sa.Column('public_access', sa.Boolean(), nullable=False),
    sa.Column('encryption_enabled', sa.Boolean(), nullable=False),
    sa.Column('logging_enabled', sa.Boolean(), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_cloud_assets_cloud_provider'), 'cloud_assets', ['cloud_provider'], unique=False)
    op.create_index(op.f('ix_cloud_assets_criticality'), 'cloud_assets', ['criticality'], unique=False)
    op.create_index(op.f('ix_cloud_assets_owner_employee_id'), 'cloud_assets', ['owner_employee_id'], unique=False)
    op.create_index(op.f('ix_cloud_assets_public_access'), 'cloud_assets', ['public_access'], unique=False)
    op.create_index(op.f('ix_cloud_assets_resource_type'), 'cloud_assets', ['resource_type'], unique=False)
    op.create_index(op.f('ix_cloud_assets_risk_level'), 'cloud_assets', ['risk_level'], unique=False)
    op.create_table('consent_records',
    sa.Column('consent_id', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('application_id', sa.String(length=20), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('consent_id')
    )
    op.create_index(op.f('ix_consent_records_application_id'), 'consent_records', ['application_id'], unique=False)
    op.create_index(op.f('ix_consent_records_consent_given'), 'consent_records', ['consent_given'], unique=False)
    op.create_index(op.f('ix_consent_records_employee_id'), 'consent_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_consent_records_revoked'), 'consent_records', ['revoked'], unique=False)
    op.create_table('controls',
    sa.Column('control_id', sa.String(length=20), nullable=False),
    sa.Column('policy_id', sa.String(length=30), nullable=False),
    sa.Column('control_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('automation_possible', sa.Boolean(), nullable=False),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.policy_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('control_id')
    )
    op.create_index(op.f('ix_controls_policy_id'), 'controls', ['policy_id'], unique=False)
    op.create_index(op.f('ix_controls_severity'), 'controls', ['severity'], unique=False)
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('device_type', sa.String(length=30), nullable=False),
    sa.Column('operating_system', sa.String(length=30), nullable=False),
    sa.Column('os_version', sa.String(length=50), nullable=False),
    sa.Column('encryption_enabled', sa.Boolean(), nullable=False),
    sa.Column('firewall_enabled', sa.Boolean(), nullable=False),
    sa.Column('antivirus_installed', sa.Boolean(), nullable=False),
    sa.Column('edr_installed', sa.Boolean(), nullable=False),
    sa.Column('compliance_status', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('last_patch_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index(op.f('ix_devices_compliance_status'), 'devices', ['compliance_status'], unique=False)
    op.create_index(op.f('ix_devices_device_type'), 'devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_devices_employee_id'), 'devices', ['employee_id'], unique=False)
    op.create_index(op.f('ix_devices_risk_level'), 'devices', ['risk_level'], unique=False)
    op.create_table('iam_records',
    sa.Column('iam_user_id', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('privileges', sa.Text(), nullable=False),
    sa.Column('privileged_account', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('inactive_days', sa.Integer(), nullable=False),
    sa.Column('last_privilege_review', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('iam_user_id')
    )
    op.create_index(op.f('ix_iam_records_employee_id'), 'iam_records', ['employee_id'], unique=True)
    op.create_index(op.f('ix_iam_records_privileged_account'), 'iam_records', ['privileged_account'], unique=False)
    op.create_table('personal_data_inventory',
    sa.Column('data_id', sa.String(length=20), nullable=False),
    sa.Column('application_id', sa.String(length=20), nullable=False),
    sa.Column('data_category', sa.String(length=100), nullable=False),
    sa.Column('purpose_of_processing', sa.String(length=100), nullable=False),
    sa.Column('retention_period', sa.String(length=50), nullable=False),
    sa.Column('third_party_sharing', sa.Boolean(), nullable=False),
    sa.Column('encryption_enabled', sa.Boolean(), nullable=False),
    sa.Column('consent_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('data_id')
    )
    op.create_index(op.f('ix_personal_data_inventory_application_id'), 'personal_data_inventory', ['application_id'], unique=False)
    op.create_index(op.f('ix_personal_data_inventory_consent_required'), 'personal_data_inventory', ['consent_required'], unique=False)
    op.create_index(op.f('ix_personal_data_inventory_data_category'), 'personal_data_inventory', ['data_category'], unique=False)
    op.create_index(op.f('ix_personal_data_inventory_third_party_sharing'), 'personal_data_inventory', ['third_party_sharing'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'COMPLIANCE_OFFICER', 'SECURITY_ANALYST', 'AUDITOR', 'EMPLOYEE', name='user_role', native_enum=False, length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(length=20), nullable=False),
    sa.Column('control_id', sa.String(length=20), nullable=False),
    sa.Column('evidence_type', sa.String(length=60), nullable=False),
    sa.Column('evidence_location', sa.String(length=500), nullable=False),
    sa.Column('collected_date', sa.Date(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('collected_automatically', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.control_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_control_id'), 'evidence', ['control_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_verified'), 'evidence', ['verified'], unique=False)
    op.create_table('risks',
    sa.Column('risk_id', sa.String(length=20), nullable=False),
    sa.Column('risk_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('business_impact', sa.String(length=200), nullable=False),
    sa.Column('likelihood', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('owner_department', sa.String(length=100), nullable=False),
    sa.Column('mapped_control_id', sa.String(length=20), nullable=True),
    sa.Column('current_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mapped_control_id'], ['controls.control_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('risk_id')
    )
    op.create_index(op.f('ix_risks_current_status'), 'risks', ['current_status'], unique=False)
    op.create_index(op.f('ix_risks_likelihood'), 'risks', ['likelihood'], unique=False)
    op.create_index(op.f('ix_risks_mapped_control_id'), 'risks', ['mapped_control_id'], unique=False)
    op.create_index(op.f('ix_risks_owner_department'), 'risks', ['owner_department'], unique=False)
    op.create_index(op.f('ix_risks_risk_name'), 'risks', ['risk_name'], unique=False)
    op.create_index(op.f('ix_risks_severity'), 'risks', ['severity'], unique=False)
    op.create_table('findings',
    sa.Column('finding_id', sa.String(length=20), nullable=False),
    sa.Column('control_id', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.String(length=20), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.control_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index(op.f('ix_findings_control_id'), 'findings', ['control_id'], unique=False)
    op.create_index(op.f('ix_findings_evidence_id'), 'findings', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_evidence_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_control_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_risks_severity'), table_name='risks')
    op.drop_index(op.f('ix_risks_risk_name'), table_name='risks')
    op.drop_index(op.f('ix_risks_owner_department'), table_name='risks')
    op.drop_index(op.f('ix_risks_mapped_control_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_likelihood'), table_name='risks')
    op.drop_index(op.f('ix_risks_current_status'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_evidence_verified'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_control_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_personal_data_inventory_third_party_sharing'), table_name='personal_data_inventory')
    op.drop_index(op.f('ix_personal_data_inventory_data_category'), table_name='personal_data_inventory')
    op.drop_index(op.f('ix_personal_data_inventory_consent_required'), table_name='personal_data_inventory')
    op.drop_index(op.f('ix_personal_data_inventory_application_id'), table_name='personal_data_inventory')
    op.drop_table('personal_data_inventory')
    op.drop_index(op.f('ix_iam_records_privileged_account'), table_name='iam_records')
    op.drop_index(op.f('ix_iam_records_employee_id'), table_name='iam_records')
    op.drop_table('iam_records')
    op.drop_index(op.f('ix_devices_risk_level'), table_name='devices')
    op.drop_index(op.f('ix_devices_employee_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_type'), table_name='devices')
    op.drop_index(op.f('ix_devices_compliance_status'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_controls_severity'), table_name='controls')
    op.drop_index(op.f('ix_controls_policy_id'), table_name='controls')
    op.drop_table('controls')
    op.drop_index(op.f('ix_consent_records_revoked'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_employee_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_consent_given'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_application_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_cloud_assets_risk_level'), table_name='cloud_assets')
    op.drop_index(op.f('ix_cloud_assets_resource_type'), table_name='cloud_assets')
    op.drop_index(op.f('ix_cloud_assets_public_access'), table_name='cloud_assets')
    op.drop_index(op.f('ix_cloud_assets_owner_employee_id'), table_name='cloud_assets')
    op.drop_index(op.f('ix_cloud_assets_criticality'), table_name='cloud_assets')
    op.drop_index(op.f('ix_cloud_assets_cloud_provider'), table_name='cloud_assets')
    op.drop_table('cloud_assets')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_risk_score'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_result'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_geo_location'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_employee_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_application_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vendors_service_category'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_risk_rating'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_reports_framework'), table_name='reports')
    op.drop_index(op.f('ix_reports_compliance_status'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_policies_mandatory'), table_name='policies')
    op.drop_index(op.f('ix_policies_framework'), table_name='policies')
    op.drop_index(op.f('ix_policies_category'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_ingestion_logs_job_id'), table_name='ingestion_logs')
    op.drop_table('ingestion_logs')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_device_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_index(op.f('ix_employees_account_status'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_applications_risk_level'), table_name='applications')
    op.drop_index(op.f('ix_applications_owner_department'), table_name='applications')
    op.drop_index(op.f('ix_applications_internet_facing'), table_name='applications')
    op.drop_index(op.f('ix_applications_data_classification'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_ingestion_jobs_dataset_type'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###
